#!/bin/bash

swaymsg output DP-1 resolution 1920x1080@144Hz position 0,0
swaymsg output DP-2 resolution 1920x1080@144Hz position 1920,0

for ws in 1 3 5 7 9; do
  swaymsg workspace "$ws" output DP-1
done

for ws in 2 4 6 8 10; do
  swaymsg workspace "$ws" output DP-2
done
